### ISSUE TITLE
關於 config git 的問題 

### ISSUE THREAD

**Issue by Julienjazz** [huayinthon/huayinthon.github.io#10]
1 . 請問在terminal 下使用以下 git config 指令時，需要先安裝vagrant才能執行嗎？
> git config --global user.name "Put Your Name"
> git config --global user.email Put@Your Email Here

2. 在mac裡，我們要從哪個目錄下才可以看到上述兩個指令所做的變更呢？
   
（不好意思問得很基本，剛剛在看了這個下面連結，不過沒有很確定 。<<http://backlogtool.com/git-guide/tw/intro/intro2_2.html>>）

**Comment by jasonatfleepio** [comment]
git 應該 mac 安裝 Xcode 就會有了？你可以試試看 git -v 有沒有東西

**Comment by jasonatfleepio** [comment]
兩個是獨立的，設定 git 是方面後續的開發 ..

**Comment by jasonatfleepio** [comment]
vagrant 是協助在 "開發環境、infrastructure 的一致" ... 屬於環境面向

git 則是操作程式碼的工具

**Comment by Julienjazz** [comment]
恩，謝了. Git的部分 ，我應該沒有問題了。

**Comment by jasonatfleepio** [comment]
nice

--
