### ISSUE TITLE
發文成功但是在華陰頌blog 中無法看到，是因為SYNC有時間差嗎？

### ISSUE THREAD

**Issue by Julienjazz** [huayinthon/huayinthon.github.io#12]
在_posts裡發文成功 <<https://github.com/huayinthon/huayinthon.github.io/tree/master/_posts>>
(如下圖所標註) 
![image](https://cloud.githubusercontent.com/assets/13349452/10427031/8f822f44-7118-11e5-851a-90737b6a5741.png)
但在我們的部落格中卻看不到，是什麼原因呢？
<<http://huayinthon.github.io/blog/>>

**Comment by yuessir** [comment]
檔名用日期命名看看

**Comment by jasonatfleepio** [comment]
檔名空格都無法處理～

**Comment by Julienjazz** [comment]
感謝，我用檔名加入日期後，就可以了。抱歉沒有即時回，剛跟萬里咖啡店的老闆聊了一下。

**Comment by Julienjazz** [comment]
我想問一個假設性的問題，不是我現在切身相關的。在github裡，像這個issue處理完後，我們可以把這個 issue 從issue資料夾裡 close掉，但是把close掉的issue連同這些對話記錄移到某個資料夾做備查，每隔一段時間再清理嗎？

當然自己另外去寫close issue的summary也可以，只是很麻煩。

**Comment by jasonatfleepio** [comment]
可以用容易辨識的 label 去定義 issue 分類，所以不單是以 issue 開/關狀態來檢視。

--

**Comment by jasonatfleepio** [comment]
剛剛這個 issue 用 git commit --allow-empty -m "closed #12” && git push 關掉啦 ..
