### ISSUE TITLE
增加一個書法體

### ISSUE THREAD

**Issue by jasonatfleepio** [huayinthon/huayinthon.github.io#5]
<img width="678" alt="2015-10-09 02 52 16" src="https://cloud.githubusercontent.com/assets/15030430/10376547/f5c054a6-6e30-11e5-9b38-c9bde118c5d1.png">

**Comment by jasonatfleepio** [comment]
<img width="593" alt="2015-10-09 02 56 14" src="https://cloud.githubusercontent.com/assets/15030430/10376612/576852ee-6e31-11e5-9b99-968814d5bf04.png">

**Comment by yuessir** [comment]
還不錯

**Comment by Julienjazz** [comment]
很好看，是不是任何中文字，都可以透過這個模組轉成書法題呢？

**Comment by jasonatfleepio** [comment]
這是毛筆 生成器 哈哈

--

**Comment by jasonatfleepio** [comment]
可以 google 一下

--

**Comment by Julienjazz** [comment]
好看，真不愧是我們華陰街的藝術總監～

**Comment by jasonatfleepio** [comment]
這 issue reply 從 fleep.io 完成 又發現一個優點了

--

**Comment by jasonatfleepio** [comment]
我從這邊回  
總監咧也只是 online generator 你也可以

--

**Comment by Julienjazz** [comment]
太棒了謝謝你的解說，我也找到reply from fleep 的按鈕了。
哈，不只online generator 啊，總監還會到處跟人家小青年旅館，討藝文明信片回家貼藝術牆。哈哈 （上次我回台北住華陰街夾角拖青年旅館時，飛利浦跟我說的 ＾＾）
