### ISSUE TITLE
關於安裝與執行vagrant 的問題

### ISSUE THREAD

**Issue by Julienjazz** [huayinthon/huayinthon.github.io#9]
請問在安裝vagrant 前是否須先安裝ruby 及rubygems 呢？兩者皆需要嗎？
另外在安裝Ruby前是否須先裝 ＲＶＭ？

**Comment by jasonatfleepio** [comment]
no, vagrant 會協助 ruby/rubygems 的工具，所以只要安裝 vagrant 就好了

--

**Comment by jasonatfleepio** [comment]
devops 的開發策略，讓參與者以最少的系統複雜度，達到一致的狀態 ..

--
